# Generated by Django 6.0.7 on 2026-07-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeatPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('beat', models.CharField(choices=[('SADE', 'SADE - Afro - 100K'), ('Hold me', 'Hold me - Afro - 100K'), ('Settings', 'Settings - Private School - 150K')], max_length=50)),
                ('proof_of_payment', models.ImageField(upload_to='payment_proofs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudioBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('service', models.CharField(choices=[('Recording', 'Recording - 100K'), ('Mixing', 'Mixing - 200K'), ('Mastering', 'Mastering - 100K'), ('Full Production', 'Full Production - 400K')], max_length=50)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('project_title', models.CharField(blank=True, max_length=150)),
                ('message', models.TextField(blank=True)),
                ('proof_of_payment', models.ImageField(upload_to='payment_proofs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
