# Generated by Django 6.0.7 on 2026-07-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beatpurchase',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='studiobooking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='beatpurchase',
            name='beat',
            field=models.CharField(choices=[('SADE', 'SADE - Afro - ₦100,000'), ('Hold me', 'Hold me - Afro - ₦100,000'), ('Settings', 'Settings - Private School - ₦150,000')], max_length=50),
        ),
        migrations.AlterField(
            model_name='studiobooking',
            name='service',
            field=models.CharField(choices=[('Recording', 'Recording - ₦100,000'), ('Mixing', 'Mixing - ₦200,000'), ('Mastering', 'Mastering - ₦100,000'), ('Full Production', 'Full Production - ₦400,000')], max_length=50),
        ),
    ]
